version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./results:/app/results:rw
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
      - FLASK_APP=app.py
    command: python app.py
    
  cli:
    build: .
    volumes:
      - ./results:/app/results:rw
    environment:
      - PYTHONUNBUFFERED=1
      - MPLBACKEND=Agg
      - MPLCONFIGDIR=/tmp/matplotlib
    command: python main.py
    profiles:
      - cli